name: Latest image build

on:
  push:
    branches: [ "main" ]

jobs:
  latest-image-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Config DockerHub
        uses: docker/login-action@v3
        with:
          registry: reg.haijin666.top
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@v0.6

      - name: build and publish image
        run: |
          export KO_DOCKER_REPO=reg.haijin666.top/cloudpilotai/karpenter-provider-alibabacloud
          ko build --bare github.com/chjtxwd/karpenter-provider-alibabacloud/cmd/controller
